# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('privacy', models.BooleanField()),
                ('description', models.CharField(max_length=1500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
